### ISSUE TITLE
Predicate names treated specially in posts

### ISSUE THREAD

**Issue by wouterbeek** [Anniepoo/swiplsitedesign#16]
This is probably not a bug, but I'm curious how it works.

When posting a SWI changelog as a sample news item, I saw that predicate references such as [1] are translated to DSL rules such as [2]. (This is done by `wiki_file_codes_to_dom/2`.

``` .pl
[1]   version/1
[2]   \predref(version/1)
```

Upon generating the DOM using `html(DOM)` an internal server error is thrown: "Undefined procedure: <MODULE-NAME>:predref/3"

What would be the best way to handle this?

**Comment by JanWielemaker** [comment]
On 12/28/2013 07:01 PM, Wouter Beek wrote:

> This is probably not a but, but I'm curious how it works.
> 
> When posting a SWI changelog as a sample news item, I saw that predicate
> references such as [1] are translated to DSL rules such as [2]. (This is
> done by |wiki_file_codes_to_dom/2|.
> 
> [1]   version/1
> [2]   \predref(version/1)
> 
> Upon generating the DOM using |html(DOM)| an internal server error is
> thrown: "Undefined procedure: :predref/3"
> 
> What would be the best way to handle this?

You need to import library(pldoc/doc_html) into the library that does
the wiki rendering.   I didn't check how you implemented the news feed,
but a simple way of course is to have a directory news in the www tree
and just redirect to the wiki rendering.

```
Cheers --- Jan
```

**Comment by wouterbeek** [comment]
Thanks! It works fine now.
