### ISSUE TITLE
/git/

### ISSUE THREAD

**Issue by wouterbeek** [Anniepoo/swiplsitedesign#17]
Visiting `/git/` gives an internal server error: `plgit(.)` does not exist.

I've changed [1] to [2].

``` .pl
[1]   file_search_path(plgit, plweb(git))
[2]   file_search_path(plgit, plweb('git-web'))
```

Hope this is correct!

**Comment by JanWielemaker** [comment]
On 12/28/2013 07:52 PM, Wouter Beek wrote:

> Visiting |/git/| gives an internal server error: |plgit(.)| does not exist.
> 
> I've changed [1] to [2].
> 
> [1]   file_search_path(plgit, plweb(git))
> [2]   file_search_path(plgit, plweb('git-web'))
> 
> Hope this is correct!

No.  Seems you didn't check this in.  Please don't.  git should be
a symbolic link to the git repositories of SWI-Prolog.  On my machine,
that is a link to /home/pl/git/, where all the bare repos are located.

```
--- Jan
```

**Comment by wouterbeek** [comment]
Got it, thanks!
