### ISSUE TITLE
News 

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplsitedesign#2]
From time to time Jan puts 'news' on the home page. We need a mechanism for doing this.

Possible mechanism - There will be two levels of news, normal and high.
Each piece of news has a headline and a body.

All news gets added to a generated news page. 

News also gets added to the mix of did you know facts. The probability score for new news is extremely high, but drops off rapidly.

Additionally, if the level is high, the news appears in a modal (modeless?) popup on the home page. The visitor gets a cookie so they don't get the news repeatedly.

alternatively - it could replace the big pull quote in the middle.  (on reflection, I _much_ prefer this).
The pull quote's important. In my daily use of swipl I should usually see it first, not a message about how 
7.1.4 no longer removes /etc on BeOS when plOSC is installed.

News should have a 'shelf life' setting where it turns itself off. This might be version based or time based, set by the person who adds the news.
The objective is to make sure important news gets seen, that less important changes have 'here's a chance to read about changes', and that deliberately seeking out the news it's possible to find it.

**Comment by Anniepoo** [comment]
News headlines could replace DYK at some frequency (10% or something).
This might be a way to get changelog type news more widely seen.

**Comment by Anniepoo** [comment]
Ok, a more detailed note about news.

The motivation for having some complicated handling of news is that we want our visitors to:
1. Be able to deliberately get the news. That's straightforward enough - have a news page, add news item to community menu under Support that links there.
2. Offer users news. This is a bit tricky because we're stealing the space for the pull quote on the home page. But we _DON'T_ want to give visitors news if we think they're a first time visitor.
3. Not annoy users with news. I probably visit the SWI-Prolog website 100 times a day. Being offered the same news over and over means I stop reading the news.
4. If I'm being offered news stochastically, I shouldn't be baffled how to get back to it.
   If I load the webpage and there's a big announcement that the latest windows nightlies are formatting the hard drive on install, it shouldn't be hard to get the news again.

User scenarios -
Some awful or great thing is happening (eg the 7 rev). I visit the swipl home page. I should def see the news. I reload, maybe 50% chance of seeing, and then 25% for the next 2, then 12% for next 4 and so on. If the news is time limited it doesn't show after it's stale (eg Christmas greeting).

Something of less importance occurs. I should only see the news if I'm a return visitor. First time visitors should get the pull quote, not news, unless the news is critical.

scenario we don't want - 
The pull quote is replaced by the changelog

Visually, if we start news with a headline in bold, it'll be visually distinct from the pull quote.

**Comment by JanWielemaker** [comment]
Agree.  Is a news item going to be a blob-post like item entered in Wiki format?  If considered useful,
I can take care of the infrastructure to add news items seamlessly to the overall manual infrastructure
(such that that can me commented, tagged and searched).

**Comment by Anniepoo** [comment]
wouters on this, Encourage you to not expand the scope of this item, it was intended as a minor thing, just something to avoid the random changes to home page we've been doing, and encourage people to look at the summary of change info.
Generating news should def require higher than edit the wiki priviledges. I was going to just define a fact in a file. That requeirs zero extra code to support it, 8cD we're not in java, our code can actually read our code.

**Comment by wouterbeek** [comment]
News has freshness lifetime and age, and is either fresh or stale
(terms inspired by RFC 2616 / HTTP 1.1).

The following has been implemented:
- Fresh news page: `/news`
- Fresh and stale news page: `/news/archive`
- Each news item has a page: `/news/92a87df631c11e3234c6ad8133c9ecdbbe15caf7`
- News mixes in with the "did-you-know-?" bar. Not sure whether this is wanted.
- User avatars; dateTime stamp; meta-tags (only `News` for now).
- Editor for adding new news items (reusing annotation editor): `/add_news`

![news](https://f.cloud.github.com/assets/1685012/1812473/b3132580-6e7c-11e3-80d9-f8fd63a714cc.png)

Now comes the difficult part:
- News has an importance and a freshness lifespan.
- We want news to be shown when it is **relevant**. Two types of relevance:
- News relevance that is independent of a user (e.g. SWI 7).
  - News relevance that is dependent on a specific user
    (e.g. Semweb update for an SW-researcher).

The following has been implementaed.
- New news is more relevant than old news.
- Important news is more relevant than old news.

What has not been implemented:
- Use of cookies to determine the kind of user:
  - First time visiting.
  - Often visiting.
  - Logged-in developer.

**Comment by Anniepoo** [comment]
News mixes in with the "did-you-know-?" bar. Not sure whether this is wanted. - it is wanted  8cD

Thought we were going to put esp. high relevance news in the pull quote?

**Comment by wouterbeek** [comment]
Yep, the relevance of a news item is also the probability of it ending up in the dyk bar.

**Comment by wouterbeek** [comment]
I consider the news feature 'done' for now. I will make future changes based on new issues.

**Comment by JanWielemaker** [comment]
Did you also push the stuff?  B.t.w., I get mostly

```
 Failed to translate to HTML: \did_you_know
```

which might be related (didn't try to find out; my only target for now is integration of the page layout with PlDoc).
