### ISSUE TITLE
redirect loop on localhost

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplsitedesign#21]
It would reduce the hassles of developing on the website if it were possible to talk to the website on localhost. I don't recall the site doing this before, is this due to recent work?

Anyway, there should be something tracking this problem, so here's a bug for it.

Site won't serve to localhost. on any but home page, gets an infinite redirect.

This is due to Wouters work? anyway, assigning to Jan just so it's assigned to somebody.

**Comment by JanWielemaker** [comment]
On 12/29/2013 06:04 PM, Anne Ogborn wrote:

> It would reduce the hassles of developing on the website if it were
> possible to talk to the website on localhost. I don't recall the site
> doing this before, is this due to recent work?

It seems to work fine here.  I'm currently at the master of both github
repositories, which seems to be the most recent, except for some stuff
pushed to NewFooter.

> Anyway, there should be something tracking this problem, so here's a bug
> for it.
> 
> Site won't serve to localhost. on any but home page, gets an infinite
> redirect.

The only thing I can imagine is that this happens if you try to login.
OpenID logon can only be to a publicly available system, so if you try
to login it will try a redirect to the public network.  If that doesn't
exist, I wouldn't be surprised if it can redirect again to localhost, in
a loop.

> This is due to Wouters work? anyway, assigning to Jan just so it's
> assigned to somebody.

If the above doesn't help, please tell ne exactly what you do and
your network configuration.  What does this tell you?

```
?- gethostname(Host).
```

Host is the thing it redirects to.

```
Cheers --- Jan
```

**Comment by Anniepoo** [comment]
Oh, this is very strange then.

I just pulled both plweb and plweb-www from origin master
I have a local change to download.pl that shouldn't affect anything.

?- gethostname(Host).
Host = 'anniepoo-VirtualBox'.

I'm forwarding 3040 in the virtualbox to 8000 on the host system via the virtualbox control panel.
This hasn't changed the behavior

Behavior I'm seeing: attempting to reference any page except the home page gives me this:

The webpage
 at http://localhost:8000/user/create_profile?return=/openid/login?openid.return_to%3Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%253D/openid/login?openid.return_to%25253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%2525253D/openid/login?openid.return_to%252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%25252525253D/openid/login?openid.return_to%2525252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%252525252525253D/openid/login?openid.return_to%25252525252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%2525252525252525253D/openid/login?openid.return_to%252525252525252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%25252525252525252525253D/openid/login?openid.return_to%2525252525252525252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%252525252525252525252525253D/openid/login?openid.return_to%25252525252525252525252525253Dhttp://annie
poo-VirtualBox:8000/user/create_profile?return%2525252525252525252525252525253D/openid/login?openid.return_to%252525252525252525252525252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%25252525252525252525252525252525253D/openid/login?openid.return_to%2525252525252525252525252525252525253Dhttp://anniepoo-VirtualBox:8000/user/create_profile?return%252525252525252525252525252525252525253D/pldoc/refman/ has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer.

Logging in via the fake login doesn't seem to help.

**Comment by JanWielemaker** [comment]
Hi Anne,

Are you using the ?- debug(openid_fake('Something'))?

```
--- Jan
```

**Comment by Anniepoo** [comment]
using/not using the openid_fake  I get same results.

I'm online now, won't be too much longer (I want to go out in a bit).

Can you pop up on skype?

**Comment by JanWielemaker** [comment]
Hi Anne,

I see that I can reproduce this by using the fake login, which causes
it to try and create a profile.  That seems to be where it goes wrong.
I'll briefly try and find what happens.

```
--- Jan
```

**Comment by Anniepoo** [comment]
OK, I'm staying in front of computer while that happens.
If you want, I'm on skype

**Comment by JanWielemaker** [comment]
On 12/29/2013 10:12 PM, Anne Ogborn wrote:

> OK, I'm staying in front of computer while that happens.

Fixed.  The OpenID faking was badly broken.  Please pull plweb.

```
Cheers --- Jan
```

**Comment by Anniepoo** [comment]
thanks!
