### ISSUE TITLE
Big font size and margin+padding offsets in CSS

### ISSUE THREAD

**Issue by wouterbeek** [Anniepoo/swiplsitedesign#23]
The CSS in `swipl.css` makes it difficult to develop the website. The problematic CSS is the following:

``` .css
#contents div {
    margin-left: 30px;
    margin-right: 30px;
    margin-top: 45px;
    margin-bottom: 45px;
    background-color: #FFF;
    padding: 25px 27px;
    font-size: 20pt;
    font-style: italic;
}
```

The first problem is the `font-size`, which is the size normally used on a title page (normal font sizes are in the 10-12pt range).

The second problem is the `margin` and `padding` settings, which apply to **all** `div` elements underneath `#contents`. Maybe this should be `#contents+div` (direct `div` children only). For example the markItUp editor is displayed incorrectly:

![create_profile](https://f.cloud.github.com/assets/1685012/1829546/b6598180-72d2-11e3-81a0-32b2b3f4b6f0.png)

**Comment by JanWielemaker** [comment]
Yes.  Please leave tweaking the global css to me as this needs
synchronization
between too many components.  Of course you can tweak with styling your own
things.

This indeed is not a good style rule.  I guess it is there fore the home
page.

```
Cheers --- Jan
```

**Comment by Anniepoo** [comment]
ok, so Jan, you're going to fix this?

**Comment by wouterbeek** [comment]
Done!
