### ISSUE TITLE
searching for 'static' returns some errors among the reply:

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplsitedesign#41]
Wiki pages from the website
[wiki] ERROR: No permission to modify static_procedure Name/Arity
[wiki] Warning: (file:line) Redefined static procedure: name/arity
[wiki] How to serve static files?
System Libraries

from Nicos

**Comment by JanWielemaker** [comment]
These are FAQ entries from the wiki that explain these errors :-)   If anything needs changing, I guess it is the
title of the FAQ entry.

I did change the colouring of the result table to be at least readable.  I'm still not happy about the styling of these pages.

**Comment by Anniepoo** [comment]
I'm filing a bug for styling, I'll get there when I get there.
