### ISSUE TITLE
login logout bug

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplsitedesign#53]
There's some bug in the login/logout sequence.

This evening talked Randy through getting started via phone.  So I could coach him I logged out, then tried to log back in. This confused the system, it gave me the bye message when I logged in, etc... eventually I got back to some stable logged in place.

This was an issue with the site last summer. Looks like it's reared it's ugly head again.

I grabbed my page history when it happened

https://open.login.yahoo.com/openid/op/start?z=H4EK1zF_Wkcg8N68LCfnga7Ie_DS1uCCAnMgffdddfsfdH.gy9liaudhpCM02xoCCD_tOOqp0drFklIOtQS2CwFJCPmnH7gYltFG3CbIbEJCXi.prEmCiiWzBqI3bl.3wn0NIt7ihOYwVTlcW_Vxewp4b.VffrtGHPkPIqWPcIoUI86R2U.3vBM5V8FJLpmf1QSP6WnIzxlZfPkdNQiprkKF3uFUzDDmA6EIypgn1gSxJKYdmqLSGiUbvknB9SOxdYhRuAsY0XWRV6zku2q.u9VBY.URFtD.duV4RCNV_ImQqeyzoGuGsybsa9RFLA4ow_dciZVJ4_1URfQO6NM42.1LcW4gVUkbD08P2j4wthcRNwj_g_jYHvaphurhCpeSfSi_Q--
open.login.yahoo.com

7:19 PM
SWI-Prolog login
swi-prolog.org

7:19 PM
Not logged in
swi-prolog.org

7:18 PM
https://open.login.yahoo.com/openid/op/start?z=zL3njWxSWkennmI3ES8MY5QBk.LqDjfsdfsdfsdTDfZLsw.nNHELE5Vo.SGLNcH2xHAOScbrig2_ouz60Nh2bp4jC3rWEOnBoq8TKD8H7yHfppKb2.kCMliZYnnmsXRJTzVexeiKhM7P_TXSRQ7.kN33VPqbC0vfDvyIadEzIr.hXybwZS9dGs4N2oDGGngU8O_Z_1SjhXy7YsyclEnum21D_7y915_86iffoPGEwCQUmZmJxJOiEFEHvhHHBeiit65rWNxiReZ935YYeYAavJscrqt.Jq0tUPXVKz5rKzaPFXxiLw--
open.login.yahoo.com

7:18 PM
SWI-Prolog login
swi-prolog.org

7:18 PM
https://open.login.yahoo.com/openid/op/start?z=ndXmb6MvWkeh74ZuxEKDuFi2YMzaFCXsdfsdfsdffsdfsdsdfds9ywzMDwYRNlb6qkeRmgV5dCVU3KN4ivul8RoR2GnzX0pCNK_WquR3hIhYzQXI9sLpSnd2qM1gxRYcBpJnGwM3q7b8l3IhiDawMl5mqyl8NseXaXXty25NX1.qel6ZoA1txVs02gHwQdWAUUe7ebKLufUYzWPWkWfRmOFB9z4wnpSvVW.5Q5VKCw--
open.login.yahoo.com

7:18 PM
News -- Markus Triska earned his PhD with his clp(fd) implementation
swi-prolog.org

7:18 PM
https://open.login.yahoo.com/openid/op/start?z=IX9fz9k7Wkf.XG56cGEJIA5QQyzHl547dsfsdffdssdfsdfsdfVT_GNMQsjMtHtnIzMCm2sDMObSKJn1k1VPE8J_abpD.c0kot67QNKOluQyONabiMeLIVPzRjKG3YC4hMdVLt82qvwpZRGiwETxAEQ--
open.login.yahoo.com

7:18 PM
https://open.login.yahoo.com/openid/op/start?z=lbFj4pMJWkfvcg5ile_GOm9JN6fm8LxYThvfdsdsffsddfsdsfdsfdfsdfsFZ8LGYFaRmnQT06m7IFYdxYncSgj24l.yWB9XGxOcu4rsX9JBtq4FRBkRuhpAFAF1YEw9ry6ebsm2illN2NKidMu7p.QamvbuYctpng--
open.login.yahoo.com

7:17 PM
Logged out
swi-prolog.org

7:17 PM
Request for Permission
accounts.google.com

7:17 PM
Sign in - Google Accounts
accounts.google.com

7:15 PM
Eat your own dog food
swi-prolog.org

**Comment by JanWielemaker** [comment]
I can't see much in the sequence.  There is a bug though: login returns to the page you came
from and if you first logged out, this is the logout handler.  So, logging straight back in logs you
out immediately :-(  I guess we must catch that by explicitly testing that the returnto can never
be /user/logout, and set it to / instead.

Does this explain it?

**Comment by JanWielemaker** [comment]
I fixed the above.  Running on the production site.

**Comment by Anniepoo** [comment]
Yes, that's probably what happened to me. I only logged out so I could help Randy through the login page. Closing this and filing a new bug that the openid page is confusing.
