### ISSUE TITLE
openid for plweb

### ISSUE THREAD

**Issue by wouterbeek** [Anniepoo/swiplsitedesign#9]
Allow users to login using `site_user_logged_in/1`. This currently fails.

It would also be nice to have an avatar of the user. Can we extract that from the openid server? For instance gravatar

**Comment by Anniepoo** [comment]
A long time gripe of mine is that the openid on our site works differently than any other site I've ever signed into with OpenID.  I haven't had time to look into how or why, but def. this could use some UI review.

**Comment by wouterbeek** [comment]
This is blocking my progress on the wiki footer (annotations + posts), since there are many checks for being logged in. And slightly different HTML has to be generated based on the user's login status.

**Comment by JanWielemaker** [comment]
Why is that?   The predicate to check that someone is logged on does not need to change if we change the
details of the login form.
